version: '3.8'
services:
  app:
    build: .
    ports: 
      - '8080:8080'
    depends_on:
      - db
      - nats
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports: 
      - '5432:5432'
  nats:
    image: nats:latest
    environment:
      NATS_URL: ${NATS_URL}
    ports: 
      - '4222:4222'
      - '8222:8222'