apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-app
  template:
    metadata:
      labels:
        app: notification-app
        editor: vscode
    spec:
      containers:
      - name: notification-container
        image: test-ellco/notification-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: NATS_URL
          valueFrom:
            secretKeyRef:
              name: notification-secret
              key: NATS_URL
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: notification-secret
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: notification-secret
              key: DB_PORT
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: notification-secret
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: notification-secret
              key: DB_PASS
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: notification-secret
              key: DB_NAME