apiVersion: v1 
kind: Secret 
metadata:   
  name: notification-secret
type: Qpaque
stringData:
  NATS_URL: nats://nats:4222
  DB_HOST: localhost
  DB_PORT: 5432
  DB_USER: postgres
  DB_PASS: 5564
  DB_NAME: notifications